-- AlterTable
ALTER TABLE "bill_items" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "inventory_items" ALTER COLUMN "currentQuantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalQuantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "lowStockThreshold" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "purchase_order_items" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "receivedQuantity" SET DEFAULT 0,
ALTER COLUMN "receivedQuantity" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "stock_movements" ALTER COLUMN "quantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "previousQuantity" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "newQuantity" SET DATA TYPE DOUBLE PRECISION;
