-- AlterTable
ALTER TABLE "bill_items" ALTER COLUMN "taxRate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "inventory_items" ALTER COLUMN "taxRate" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "purchase_order_items" ALTER COLUMN "taxRate" SET DATA TYPE DOUBLE PRECISION;
